/**************************************************************************/
/*                                                                        */
/*  ExStyles.h  -                                                         */
/*      Contient tous les styles additionnels pour les contrôles Windows. */
/*                                                                        */
/**************************************************************************/



/* Pour masquer le bouton d'une combobox */
# define	CBS_NOBUTTON		0x8000	
