/**************************************************************************/
/*                                                                        */
/*  Chopjet.h  -  Christian Vigh, 95/10/12.                               */
/*                                                                        */
/*  Définitions des classes gadget Cheops.                                */
/*                                                                        */
/**************************************************************************/



# if	! defined ( __CHOPJET_H__ )
# 	  define    __CHOPJET_H__

# include	"Gadgets/AutoText.h"
# include	"Gadgets/MFText.h"
# include	"Gadgets/ColorCb.h"
# include	"Gadgets/TextBtn.h"
# include	"Gadgets/ShapeBtn.h"
# include	"Gadgets/TabBtn.h"
# include	"Gadgets/MenuItem.h"
# include	"Gadgets/MenuDet.h"
# include	"Gadgets/ColorSB.h"
# include	"Gadgets/Fillet.h"
# include	"Gadgets/Gombo.h"
# include	"Gadgets/MenuWin.h"
# include	"Gadgets/FloatMnu.h"
# include	"Gadgets/ShrinkSP.h"

		
# endif  	/*  __CHOPJET_H__  */	
